### ISSUE TITLE
Publish to MavenCentral

### ISSUE THREAD

**Issue by Goooler** [patrykandpatrick/opto#2]

**Comment by patrickmichalik** [comment]
Hello! Would you be able to share the reason for this request? JitPack is relatively attractive for small libraries, as it requires little configuration. LiftApp depends on Opto, and we haven’t faced any JitPack-related issues. However, if JitPack is somehow troublesome, we’d be open to switching to Maven Central.

**Comment by Goooler** [comment]
Cause old Opto was published to MavenCentral, just want to keep the same state with it, I can't find the original issue that for some reason migrated to MavenCentral.

**Comment by patrickmichalik** [comment]
Got it. Because adding JitPack to a project is a matter of a single line of code, my suggestion would be for you to do so.

```groovy
maven { url "https://jitpack.io" }
```

With Vico, a relatively large project, the added flexibility stemming from publishing to Maven Central is certainly desirable. On the other hand, for Opto, JitPack seems to suffice and makes things a bit quicker for us. If JitPack causes any trouble, please feel free to let me know.
